### PR TITLE
add the type `citext` for table columns

### PR DESCRIPTION
**Pull request by pwbs**
modified:   src/sql.mli
modified:   src/sql_public.ml

### CODE REVIEW

**Comment by pwbs** [comment]
http://www.postgresql.org/docs/9.5/static/citext.html

**Comment by pwbs** [comment]
depends on https://github.com/darioteixeira/pgocaml/pull/23

**Comment by gasche** [comment]
We would need a comment to explicit the dependency on the Postgres and PG'OCaml versions.

That said, it seems that the current state of the PR depends on neither of those: it adds a `citext` type to the surface, but because you use `TString` to implement it will be translated into `text`, no `citext`, on the SQL side. You may want to create a new type tag `TCIString`, or add a `TString of kind` argument with `kind = Text | CIText`, and then use that in sql_internals:string_of_atom_type.

**Comment by pwbs** [comment]
@gasche thanks for your comments. I hope it's alright now. (Although I wouldn't be surprised if I missed something.)

**Comment by pwbs** [comment]
citext  is available even in 2 no-longer-supported version of PG SQL <http://www.postgresql.org/docs/8.4/static/citext.html>, so I guess there's no problem with the PG SQL version.

**Comment by gasche** [comment]
@pwbs I'm a bit worried at the idea of merging the code without being sure that it does the job. Do you have an application using Macque and citext, and would you be able to check that it works as expected?

(I'm not actually sure how to observe the difference at the Macaque level. You could use the `Check` interface to dynamically test the types, but otherwise, how would you tell the difference between the first version of the PR and the second one, only by sending Macaque-generated queries?)

**Comment by pwbs** [comment]
Oh I wouldn't have done that if it weren't for a "real world" application.
I need Eliom-base-app to work with emails that are case insensitive. I need that to be implemented in Besport.Com
So my patch does what I need it to do, I don't have any doubts about it because it's quite easy to observe it with just a very few tests. What I won't bet on is if it's properly done or not because I had never looked at macaque before today, and I tried to make the fewest changes possible.
I have proposed today 3 patches for software I don't work on, to address this matter, and I guarantee it was not for the fun of it. Cheers,

Philippe Wang
(mail sent from a phone)

**Comment by pwbs** [comment]
Sorry my previous long text didn't really answer all your questions. It's not easy on a phone at midnight...

To be brief this time: I don't really know how to test this patch other than just using it with an application that needs it... And see if it does the job.


Philippe Wang
(mail sent from a phone)

**Comment by gasche** [comment]
Just to clarify: have you *already* tested your application with the proposed Macaque change? If yes, I'll merge your PR immediately. If not, I would encourage you to try it first, in case you need other changes.

**Comment by pwbs** [comment]
Ok, so, it worked without `TCIString` but my first attempt with `TCIString` was a failure.

Now, after a few `git push -f`s, it seems to work fine. (I've just done some testing with the EBA distillery default template, and with the code of besport.com)

**Comment by gasche** [comment]
Thanks!

**Comment by gasche** [comment]
It may make sense to make a new release with this feature. @vasilisp , do you have an opinion on this?

**Comment by vasilisp** [comment]
@gasche, it is not urgent, but a 0.7.3 with this wouldn't harm. One less thing to pin :).

**Comment by gasche** [comment]
@vasilisp I just pushed [a tag](https://github.com/ocsigen/macaque/releases/tag/0.7.3). Would you mind doing the opam-repository part?

**Comment by vasilisp** [comment]
@gasche thanks! I will take care of the OPAM part.

Just to clarify: this works fine with `pgocaml 2.2`, right?

**Comment by pwbs** [comment]
I think it won't work with `pgocaml 2.2`. 

I had to do some changes in `pgocaml` to add `citext`: https://github.com/darioteixeira/pgocaml/pull/23

**Comment by vasilisp** [comment]
@pwbs, I don't understand. darioteixeira/pgocaml#23 only touches the Camlp4 extension, which doesn't seem to be used by Macaque.

**Comment by pwbs** [comment]
@vasilisp I guess you're right!

**Comment by vasilisp** [comment]
@gasche, I ended up tagging and submitting a 0.7.4 (ocaml/opam-repository#5637). See ocaml/opam-repository#5630 for the reason. I hope that's OK with you.

**Comment by gasche** [comment]
This if of course fine.

**Pull request merged**
